// Keybind data extracted from JetBrains PyCharm Reference Card
const KEYBINDS = [
  // MASTER YOUR IDE
  { id: "find_action", category: "Master Your IDE", action: "Find action…", keybind: "Ctrl+Shift+A" },
  { id: "tool_window", category: "Master Your IDE", action: "Open a tool window", keybind: "Alt+[0-9]" },
  { id: "synchronize", category: "Master Your IDE", action: "Synchronize", keybind: "Ctrl+Alt+Y" },
  { id: "switch_scheme", category: "Master Your IDE", action: "Quick switch scheme…", keybind: "Ctrl+`" },
  { id: "settings", category: "Master Your IDE", action: "Settings…", keybind: "Ctrl+Alt+S" },
  { id: "jump_source_nav_1", category: "Master Your IDE", action: "Jump to source", keybind: "F4" },
  { id: "jump_source_nav_2", category: "Master Your IDE", action: "navigation bar", keybind: "Alt+Home" },
  { id: "jump_last_tool", category: "Master Your IDE", action: "Jump to last tool window", keybind: "F12" },
  { id: "hide_tool_windows_1", category: "Master Your IDE", action: "Hide active", keybind: "Shift+Esc" },
  { id: "hide_tool_windows_2", category: "Master Your IDE", action: "all tool windows", keybind: "Ctrl+Shift+F12" },
  { id: "next_prev_tab_1", category: "Master Your IDE", action: "Go to next", keybind: "Alt+Right" },
  { id: "next_prev_tab_2", category: "Master Your IDE", action: "previous editor tab", keybind: "Alt+Left" },
  { id: "go_to_editor", category: "Master Your IDE", action: "Go to editor (from tool window)", keybind: "Esc" },
  { id: "close_tab_window_1", category: "Master Your IDE", action: "Close active tab", keybind: "Ctrl+Shift+F4" },
  { id: "close_tab_window_2", category: "Master Your IDE", action: "window", keybind: "Ctrl+F4", kde: true },

  // FIND EVERYTHING
  { id: "search_everywhere", category: "Find Everything", action: "Search everywhere", keybind: "Double Shift" },
  { id: "find_replace_1", category: "Find Everything", action: "Find", keybind: "Ctrl+F" },
  { id: "find_replace_2", category: "Find Everything", action: "replace", keybind: "Ctrl+R" },
  { id: "find_replace_path_1", category: "Find Everything", action: "Find in path", keybind: "Ctrl+Shift+F" },
  { id: "find_replace_path_2", category: "Find Everything", action: "Replace in path", keybind: "Ctrl+Shift+R" },
  { id: "next_prev_occurrence_1", category: "Find Everything", action: "Next", keybind: "F3" },
  { id: "next_prev_occurrence_2", category: "Find Everything", action: "previous occurrence", keybind: "Shift+F3" },
  { id: "find_word_caret", category: "Find Everything", action: "Find word at caret", keybind: "Ctrl+F3", kde: true },
  { id: "go_class_file_1", category: "Find Everything", action: "Go to class", keybind: "Ctrl+N", conflicts: true },
  { id: "go_class_file_2", category: "Find Everything", action: "file", keybind: "Ctrl+Shift+N", conflicts: true },
  { id: "go_file_member", category: "Find Everything", action: "Go to file member", keybind: "Ctrl+F12" },
  { id: "go_symbol", category: "Find Everything", action: "Go to symbol", keybind: "Ctrl+Alt+Shift+N" },

  // NAVIGATE FROM SYMBOLS
  { id: "declaration", category: "Navigate From Symbols", action: "Declaration", keybind: "Ctrl+B" },
  { id: "type_declaration", category: "Navigate From Symbols", action: "Type declaration (JS only)", keybind: "Ctrl+Shift+B" },
  { id: "super_method", category: "Navigate From Symbols", action: "Super method", keybind: "Ctrl+U" },
  { id: "implementations", category: "Navigate From Symbols", action: "Implementation(s)", keybind: "Ctrl+Alt+B" },
  { id: "find_usages_1", category: "Navigate From Symbols", action: "Find usages", keybind: "Alt+F7" },
  { id: "find_usages_2", category: "Navigate From Symbols", action: "Find usages in file", keybind: "Ctrl+F7", kde: true },
  { id: "highlight_usages", category: "Navigate From Symbols", action: "Highlight usages in file", keybind: "Ctrl+Shift+F7" },
  { id: "show_usages", category: "Navigate From Symbols", action: "Show usages", keybind: "Ctrl+Alt+F7" },

  // REFACTOR AND CLEAN UP
  { id: "refactor_this", category: "Refactor and Clean Up", action: "Refactor this…", keybind: "Ctrl+Alt+Shift+T" },
  { id: "copy_move_1", category: "Refactor and Clean Up", action: "Copy…", keybind: "F5" },
  { id: "copy_move_2", category: "Refactor and Clean Up", action: "Move…", keybind: "F6" },
  { id: "safe_delete", category: "Refactor and Clean Up", action: "Safe delete…", keybind: "Alt+Delete" },
  { id: "rename", category: "Refactor and Clean Up", action: "Rename…", keybind: "Shift+F6" },
  { id: "change_signature", category: "Refactor and Clean Up", action: "Change signature…", keybind: "Ctrl+F6" },
  { id: "inline", category: "Refactor and Clean Up", action: "Inline…", keybind: "Ctrl+Alt+N" },
  { id: "extract_method", category: "Refactor and Clean Up", action: "Extract method", keybind: "Ctrl+Alt+M" },
  { id: "introduce_var_param_1", category: "Refactor and Clean Up", action: "Introduce variable", keybind: "Ctrl+Alt+V" },
  { id: "introduce_var_param_2", category: "Refactor and Clean Up", action: "parameter", keybind: "Ctrl+Alt+P" },
  { id: "introduce_field_const_1", category: "Refactor and Clean Up", action: "Introduce field", keybind: "Ctrl+Alt+F" },
  { id: "introduce_field_const_2", category: "Refactor and Clean Up", action: "constant", keybind: "Ctrl+Alt+C" },
  { id: "reformat_code", category: "Refactor and Clean Up", action: "Reformat code", keybind: "Ctrl+Alt+L", kde: true },

  // CREATE AND EDIT
  { id: "intention_actions", category: "Create and Edit", action: "Show intention actions", keybind: "Alt+Enter" },
  { id: "basic_completion", category: "Create and Edit", action: "Basic code completion", keybind: "Ctrl+Space" },
  { id: "smart_completion", category: "Create and Edit", action: "Smart code completion", keybind: "Ctrl+Shift+Space" },
  { id: "type_completion", category: "Create and Edit", action: "Type name completion", keybind: "Ctrl+Alt+Space" },
  { id: "complete_statement", category: "Create and Edit", action: "Complete statement", keybind: "Ctrl+Shift+Enter" },
  { id: "param_context_1", category: "Create and Edit", action: "Parameter info", keybind: "Ctrl+P" },
  { id: "param_context_2", category: "Create and Edit", action: "context info", keybind: "Alt+Q" },
  { id: "quick_definition", category: "Create and Edit", action: "Quick definition", keybind: "Ctrl+Shift+I" },
  { id: "quick_external_doc_1", category: "Create and Edit", action: "Quick", keybind: "Ctrl+Q" },
  { id: "quick_external_doc_2", category: "Create and Edit", action: "external documentation", keybind: "Shift+F1" },
  { id: "generate_code", category: "Create and Edit", action: "Generate code", keybind: "Alt+Insert" },
  { id: "override_implement_1", category: "Create and Edit", action: "Override", keybind: "Ctrl+O" },
  { id: "override_implement_2", category: "Create and Edit", action: "implement members", keybind: "Ctrl+I" },
  { id: "surround_with", category: "Create and Edit", action: "Surround with…", keybind: "Ctrl+Alt+T", kde: true },
  { id: "line_comment", category: "Create and Edit", action: "Comment with line comment", keybind: "Ctrl+/" },
  { id: "extend_shrink_1", category: "Create and Edit", action: "Extend", keybind: "Ctrl+W", conflicts: true },
  { id: "extend_shrink_2", category: "Create and Edit", action: "shrink selection", keybind: "Ctrl+Shift+W" },
  { id: "optimize_imports", category: "Create and Edit", action: "Optimize imports", keybind: "Ctrl+Alt+O" },
  { id: "auto_indent", category: "Create and Edit", action: "Auto-indent lines", keybind: "Ctrl+Alt+I" },
  { id: "cut_copy_paste_1", category: "Create and Edit", action: "Cut", keybind: "Ctrl+X" },
  { id: "cut_copy_paste_2", category: "Create and Edit", action: "Copy", keybind: "Ctrl+C" },
  { id: "cut_copy_paste_3", category: "Create and Edit", action: "Paste", keybind: "Ctrl+V" },
  { id: "copy_doc_path", category: "Create and Edit", action: "Copy document path", keybind: "Ctrl+Shift+C" },
  { id: "paste_history", category: "Create and Edit", action: "Paste from clipboard history", keybind: "Ctrl+Shift+V" },
  { id: "duplicate_line", category: "Create and Edit", action: "Duplicate current line or selection", keybind: "Ctrl+D" },
  { id: "move_line_1", category: "Create and Edit", action: "Move line up", keybind: "Ctrl+Shift+Up" },
  { id: "move_line_2", category: "Create and Edit", action: "down", keybind: "Ctrl+Shift+Down" },
  { id: "delete_line", category: "Create and Edit", action: "Delete line at caret", keybind: "Ctrl+Y" },
  { id: "join_split_line_1", category: "Create and Edit", action: "Join", keybind: "Ctrl+Shift+J" },
  { id: "join_split_line_2", category: "Create and Edit", action: "split line", keybind: "Ctrl+Enter" },
  { id: "new_line", category: "Create and Edit", action: "Start new line", keybind: "Shift+Enter" },
  { id: "toggle_case", category: "Create and Edit", action: "Toggle case", keybind: "Ctrl+Shift+U" },
  { id: "expand_collapse_1", category: "Create and Edit", action: "Expand", keybind: "Ctrl+NumPad+" },
  { id: "expand_collapse_2", category: "Create and Edit", action: "collapse code block", keybind: "Ctrl+NumPad-" },
  { id: "expand_collapse_all_1", category: "Create and Edit", action: "Expand", keybind: "Ctrl+Shift+NumPad+" },
  { id: "expand_collapse_all_2", category: "Create and Edit", action: "collapse all", keybind: "Ctrl+Shift+NumPad-" },
  { id: "save_all", category: "Create and Edit", action: "Save all", keybind: "Ctrl+S" },

  // VERSION CONTROL
  { id: "vcs_popup", category: "Version Control", action: "VCS operations popup…", keybind: "Alt+`" },
  { id: "commit", category: "Version Control", action: "Commit", keybind: "Ctrl+K" },
  { id: "update_project", category: "Version Control", action: "Update project", keybind: "Ctrl+T", conflicts: true },
  { id: "recent_changes", category: "Version Control", action: "Recent changes", keybind: "Alt+Shift+C" },
  { id: "revert", category: "Version Control", action: "Revert", keybind: "Ctrl+Alt+Z" },
  { id: "push", category: "Version Control", action: "Push…", keybind: "Ctrl+Shift+K" },
  { id: "next_prev_change_1", category: "Version Control", action: "Next", keybind: "Ctrl+Alt+Shift+Down" },
  { id: "next_prev_change_2", category: "Version Control", action: "previous change", keybind: "Ctrl+Alt+Shift+Up" },

  // ANALYZE AND EXPLORE
  { id: "show_error", category: "Analyze and Explore", action: "Show error description", keybind: "Ctrl+F1", kde: true },
  { id: "next_prev_error_1", category: "Analyze and Explore", action: "Next", keybind: "F2" },
  { id: "next_prev_error_2", category: "Analyze and Explore", action: "previous highlighted error", keybind: "Shift+F2" },
  { id: "run_inspection", category: "Analyze and Explore", action: "Run inspection by name…", keybind: "Ctrl+Alt+Shift+I" },
  { id: "type_call_hierarchy_1", category: "Analyze and Explore", action: "Type", keybind: "Ctrl+H" },
  { id: "type_call_hierarchy_2", category: "Analyze and Explore", action: "call hierarchy", keybind: "Ctrl+Alt+H" },

  // NAVIGATE IN CONTEXT
  { id: "select_in", category: "Navigate In Context", action: "Select in…", keybind: "Alt+F1", kde: true },
  { id: "recent_viewed_locations_1", category: "Navigate In Context", action: "Recently viewed", keybind: "Ctrl+E" },
  { id: "recent_viewed_locations_2", category: "Navigate In Context", action: "recent locations", keybind: "Ctrl+Shift+E" },
  { id: "last_edit_location", category: "Navigate In Context", action: "Last edit location", keybind: "Ctrl+Shift+Backspace" },
  { id: "navigate_back_forward_1", category: "Navigate In Context", action: "Navigate back", keybind: "Ctrl+Alt+Left" },
  { id: "navigate_back_forward_2", category: "Navigate In Context", action: "forward", keybind: "Ctrl+Alt+Right" },
  { id: "prev_next_method_1", category: "Navigate In Context", action: "Go to previous", keybind: "Alt+Up" },
  { id: "prev_next_method_2", category: "Navigate In Context", action: "next method", keybind: "Alt+Down" },
  { id: "go_line_column", category: "Navigate In Context", action: "Go to line / column…", keybind: "Ctrl+G" },
  { id: "code_block_end_start_1", category: "Navigate In Context", action: "Go to code block end", keybind: "Ctrl+]" },
  { id: "code_block_end_start_2", category: "Navigate In Context", action: "start", keybind: "Ctrl+[" },
  { id: "add_favorites", category: "Navigate In Context", action: "Add to favorites", keybind: "Alt+Shift+F" },
  { id: "toggle_bookmark", category: "Navigate In Context", action: "Toggle bookmark", keybind: "F11" },
  { id: "toggle_bookmark_mnemonic", category: "Navigate In Context", action: "Toggle bookmark with mnemonic", keybind: "Ctrl+F11" },
  { id: "go_numbered_bookmark", category: "Navigate In Context", action: "Go to numbered bookmark", keybind: "Ctrl+[0-9]" },
  { id: "show_bookmarks", category: "Navigate In Context", action: "Show bookmarks", keybind: "Shift+F11" },

  // BUILD, RUN, AND DEBUG
  { id: "run_context", category: "Build, Run, and Debug", action: "Run context configuration", keybind: "Ctrl+Shift+F10" },
  { id: "run_debug_selected_1", category: "Build, Run, and Debug", action: "Run", keybind: "Alt+Shift+F10" },
  { id: "run_debug_selected_2", category: "Build, Run, and Debug", action: "debug selected configuration", keybind: "F9" },
  { id: "run_debug_current_1", category: "Build, Run, and Debug", action: "Run", keybind: "Shift+F10" },
  { id: "run_debug_current_2", category: "Build, Run, and Debug", action: "debug current configuration", keybind: "F9" },
  { id: "step_over_into_1", category: "Build, Run, and Debug", action: "Step over", keybind: "F8" },
  { id: "step_over_into_2", category: "Build, Run, and Debug", action: "into", keybind: "F7" },
  { id: "smart_step_into", category: "Build, Run, and Debug", action: "Smart step into", keybind: "Shift+F7" },
  { id: "step_out", category: "Build, Run, and Debug", action: "Step out", keybind: "Shift+F8" },
  { id: "run_to_cursor_1", category: "Build, Run, and Debug", action: "Run to cursor", keybind: "Alt+F9" },
  { id: "run_to_cursor_2", category: "Build, Run, and Debug", action: "Force run to cursor", keybind: "Ctrl+Alt+F9" },
  { id: "show_execution", category: "Build, Run, and Debug", action: "Show execution point", keybind: "Alt+F10" },
  { id: "evaluate_expression", category: "Build, Run, and Debug", action: "Evaluate expression…", keybind: "Alt+F8" },
  { id: "stop", category: "Build, Run, and Debug", action: "Stop", keybind: "Ctrl+F2", kde: true },
  { id: "stop_background", category: "Build, Run, and Debug", action: "Stop background processes…", keybind: "Ctrl+Shift+F2" },
  { id: "resume_program", category: "Build, Run, and Debug", action: "Resume program", keybind: "F9" },
  { id: "toggle_breakpoint", category: "Build, Run, and Debug", action: "Toggle line breakpoint", keybind: "Ctrl+F8" },
  { id: "toggle_temp_breakpoint", category: "Build, Run, and Debug", action: "Toggle temporary line breakpoint", keybind: "Ctrl+Alt+Shift+F8" },
  { id: "edit_breakpoint", category: "Build, Run, and Debug", action: "Edit / view breakpoint", keybind: "Ctrl+Shift+F8" }
];

const CATEGORIES = [...new Set(KEYBINDS.map(k => k.category))];

const CATEGORY_ICONS = {
  "Master Your IDE": "🖥️",
  "Find Everything": "🔍",
  "Navigate From Symbols": "🧭",
  "Refactor and Clean Up": "♻️",
  "Create and Edit": "✏️",
  "Version Control": "🔀",
  "Analyze and Explore": "🔬",
  "Navigate In Context": "📍",
  "Build, Run, and Debug": "🛠️"
};

const LEVEL_THRESHOLDS = [0, 100, 300, 600, 1000, 1600, 2400, 3500, 5000, 7000, 10000, 14000, 20000, 28000, 40000];

const ACHIEVEMENTS = [
  { id: "first_session", name: "🌱 First Steps", desc: "Complete your first session", check: s => s.totalSessions >= 1 },
  { id: "ten_sessions", name: "🔟 Dedicated", desc: "Complete 10 sessions", check: s => s.totalSessions >= 10 },
  { id: "fifty_sessions", name: "🎓 Veteran", desc: "Complete 50 sessions", check: s => s.totalSessions >= 50 },
  { id: "first_perfect", name: "💯 Perfect Session", desc: "Get 100% in a session (min 5 cards)", check: s => s.perfectSessions >= 1 },
  { id: "streak_5", name: "🔥 On Fire", desc: "Get a streak of 5 correct", check: s => s.bestStreak >= 5 },
  { id: "streak_10", name: "🌟 Unstoppable", desc: "Get a streak of 10 correct", check: s => s.bestStreak >= 10 },
  { id: "streak_20", name: "⚡ Legendary", desc: "Get a streak of 20 correct", check: s => s.bestStreak >= 20 },
  { id: "learn_10", name: "📚 Getting Started", desc: "Learn 10 keys", check: s => s.keysLearned >= 10 },
  { id: "learn_25", name: "📖 Halfway There", desc: "Learn 25 keys", check: s => s.keysLearned >= 25 },
  { id: "learn_all", name: "🏆 Master", desc: "Learn all keys", check: s => s.keysLearned >= KEYBINDS.length },
  { id: "level_5", name: "⭐ Level 5", desc: "Reach level 5", check: s => s.level >= 5 },
  { id: "level_10", name: "👑 Level 10", desc: "Reach level 10", check: s => s.level >= 10 },
  { id: "daily_streak_3", name: "📅 Consistent", desc: "3-day login streak", check: s => s.currentStreak >= 3 },
  { id: "daily_streak_7", name: "🗓️ Week Warrior", desc: "7-day login streak", check: s => s.currentStreak >= 7 },
  { id: "xp_1000", name: "💎 1K XP", desc: "Earn 1000 total XP", check: s => s.totalXP >= 1000 },
  { id: "xp_5000", name: "💠 5K XP", desc: "Earn 5000 total XP", check: s => s.totalXP >= 5000 },
];
